#!/bin/sh
#
#  Installs my Neovim environment into my $HOME directory.
#
#

export scriptName=nvInstall

### Setup

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
NVIM_GIT_REPO="${NVIM_GIT_REPO:=$HOME/devel/nvim}"
umask 0022

cd "$NVIM_GIT_REPO" || {
   printf "\\nError: Failed to cd into '%s'\\n" "$NVIM_GIT_REPO"
   return 1
}

### Source install infrastructure if necessary
. ./installInclude.sh

NVIM_FILES='
   ftplugin/c.lua
   ftplugin/cpp.lua
   ftplugin/fish.lua
   ftplugin/haskell.lua
   ftplugin/help.lua
   ftplugin/html.lua
   ftplugin/lua.lua
   ftplugin/markdown.lua
   ftplugin/ocaml.lua
   ftplugin/rust.lua
   ftplugin/sbt.lua
   ftplugin/scala.lua
   ftplugin/sh.lua
   lua/grs/config/autocmds.lua
   lua/grs/config/colors.lua
   lua/grs/config/globals.lua
   lua/grs/config/keymaps.lua
   lua/grs/config/tooling.lua
   lua/grs/config/options.lua
   lua/grs/lib/functional.lua
   lua/grs/lib/text.lua
   lua/grs/plugins/editor/init.lua
   lua/grs/plugins/editor/colorscheme.lua
   lua/grs/plugins/editor/telescope.lua
   lua/grs/plugins/editor/textedit.lua
   lua/grs/plugins/editor/whichkey.lua
   lua/grs/plugins/lsp/init.lua
   lua/grs/plugins/lsp/cmp.lua
   lua/grs/plugins/lsp/lsp.lua
   lua/grs/plugins/lsp/rust.lua
   lua/grs/plugins/lsp/scala.lua
   lua/grs/plugins/lsp/utils.lua
   lua/grs/plugins/tooling/init.lua
   lua/grs/plugins/tooling/mason.lua
   lua/grs/plugins/tooling/treesitter.lua
   lua/grs/plugins/tooling/utils.lua
   lua/grs/plugins/lazy.lua
   init.lua
'

NVIM_TOML='
   selene.toml
   stylua.toml
   vim.toml
'

RM_TARGET_ITEMS="
   $XDG_CONFIG_HOME/nvim/lua/grs/utils
   $XDG_CONFIG_HOME/nvim/lua/grs/plugins/ide
"

### Install or Check

# Install Neovim files
for nvim_file in $NVIM_FILES
do
   install_file "$XDG_CONFIG_HOME/nvim" "$nvim_file" . 0644 "$switch"
done
chmod 0755 "$XDG_CONFIG_HOME"/nvim

# Install $NVIM_TOML files from repo root to $XDG_CONFIG_HOME/nvim
#
#   Note: These don't seam to work in the repo
#         unless located at repo's root.
#
for toml_file in $NVIM_TOML
do
   install_file "$XDG_CONFIG_HOME/nvim" "$toml_file" . 0644 "$switch"
done

### Some final tweaks, checks & cleanup

# Remove/report no longer needed files and directories
for item in $RM_TARGET_ITEMS
do
   remove_item "$item" target
done

# Some final adjustments/tweaks/tasks
case "$switch" in
   install)
      :
      ;;
   repo)
      # Get git status info on repo
      printf '\nGit Status:\n'
      git status -s
      ;;
   target)
      :
      ;;
esac
